In [37]:
import torch
import math

max_len = 5
seq_len = 3
batch_size = 3
d_model = 4

x = torch.arange(0, max_len * batch_size * d_model)  # 生成随机的 3D 输入张量
x.size()
y = x.reshape(max_len, batch_size, d_model)  # 生成随机的 3D 输入张量
y.size()
# 为什么接下来这四行效果一样？
print(y[:,:,:2])

tensor([[[ 0,  1],
         [ 4,  5],
         [ 8,  9]],

        [[12, 13],
         [16, 17],
         [20, 21]],

        [[24, 25],
         [28, 29],
         [32, 33]],

        [[36, 37],
         [40, 41],
         [44, 45]],

        [[48, 49],
         [52, 53],
         [56, 57]]])


In [30]:
import torch

# 创建一个张量
y = torch.arange(0, 12).reshape(3, 4)
print("Original tensor y:")
print(y)

# 创建一个切片
slice_y = y[:2, :3]
print("Slice of y:")
print(slice_y)

# 修改切片
slice_y[0, 0] = 99

print("Modified slice_y:")
print(slice_y)

print("Original tensor y after modifying slice_y:")
print(y)


Original tensor y:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
Slice of y:
tensor([[0, 1, 2],
        [4, 5, 6]])
Modified slice_y:
tensor([[99,  1,  2],
        [ 4,  5,  6]])
Original tensor y after modifying slice_y:
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [31]:
lst = [0, 1, 2, 3, 4]
slice_lst = lst[1:4]
slice_lst[0] = 99

print("Original list:", lst)         # [0, 1, 2, 3, 4]
print("Slice of list:", slice_lst)  # [99, 2, 3]


Original list: [0, 1, 2, 3, 4]
Slice of list: [99, 2, 3]


In [34]:
tup = (0, 1, 2, 3, 4)
slice_tup = tup[1:4]
slice_tup[0]

print("Original tuple:", tup)       # (0, 1, 2, 3, 4)
print("Slice of tuple:", slice_tup) # (1, 2, 3)


Original tuple: (0, 1, 2, 3, 4)
Slice of tuple: (1, 2, 3)
